[package]
name = "iridium"
version = "0.1.0"
authors = ["nownabe <nownabe@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "^4.0"
clap = { version = "2.32", features = ["yaml"] }
